# Generated by Django 3.2.5 on 2022-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('kcal', models.FloatField(default=0.0)),
                ('tan', models.FloatField(default=0.0)),
                ('dang', models.FloatField(default=0.0)),
                ('ji', models.FloatField(default=0.0)),
                ('dan', models.FloatField(default=0.0)),
                ('kalsum', models.FloatField(default=0.0)),
                ('inn', models.FloatField(default=0.0)),
                ('salt', models.FloatField(default=0.0)),
                ('kalum', models.FloatField(default=0.0)),
                ('magnesum', models.FloatField(default=0.0)),
                ('chul', models.FloatField(default=0.0)),
                ('ayeon', models.FloatField(default=0.0)),
                ('kolest', models.FloatField(default=0.0)),
                ('transfat', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usr_name', models.CharField(max_length=10)),
                ('usr_sex', models.CharField(max_length=2)),
                ('usr_height', models.IntegerField(default=0)),
                ('user_weight', models.FloatField(default=0.0)),
            ],
        ),
    ]
