# Generated by Django 3.2.5 on 2022-04-11 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 17, 35, 41, 20155)),
        ),
    ]
