# Generated by Django 3.2.5 on 2022-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='foodimage',
            field=models.ImageField(blank=True, upload_to='eat/images/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_kcal',
            field=models.FloatField(default=1620.0),
        ),
        migrations.AddField(
            model_name='login',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_height',
            field=models.FloatField(default=0.0),
        ),
    ]
