# Generated by Django 3.2.5 on 2022-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_auto_20220411_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodimage', models.ImageField(blank=True, upload_to='eat/images/%y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_kcal',
            field=models.FloatField(default=0.0),
        ),
    ]
