# Generated by Django 3.2.5 on 2022-04-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_alter_login_recommend_dang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='user_idx',
            new_name='user_id',
        ),
    ]
