# Generated by Django 3.2.5 on 2022-04-12 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_diet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='imgs',
            name='foodimage',
        ),
        migrations.AddField(
            model_name='imgs',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='eat/images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 12, 8, 10, 7, 787309, tzinfo=utc)),
        ),
    ]
