# Generated by Django 3.2.5 on 2022-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_rename_user_idx_diet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='wanted_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
