# Generated by Django 3.2.5 on 2022-04-12 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_auto_20220412_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RenameField(
            model_name='imgs',
            old_name='food_image',
            new_name='foodimage',
        ),
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 12, 8, 58, 44, 640267, tzinfo=utc)),
        ),
    ]
