# Generated by Django 3.2.5 on 2022-04-14 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_auto_20220412_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='recommend_ayeon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_cul',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_dan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_dang',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_inn',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_ji',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_kal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_kalum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_kolest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_magnesum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_salt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_tan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_transfat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
