# Generated by Django 3.2.5 on 2022-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_login_wanted_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='momentum',
            field=models.IntegerField(default=0),
        ),
    ]
