# Generated by Django 3.2.5 on 2022-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0005_auto_20220414_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='recommend_kal',
        ),
        migrations.AddField(
            model_name='login',
            name='recommend_kalsum',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_ayeon',
            field=models.FloatField(default=0.012),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_cul',
            field=models.FloatField(default=0.015),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_dan',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_inn',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_ji',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_kalum',
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_kcal',
            field=models.FloatField(default=2400.0),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_kolest',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_magnesum',
            field=models.FloatField(default=0.22),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_salt',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='login',
            name='recommend_tan',
            field=models.FloatField(default=500.0),
        ),
    ]
