# Generated by Django 4.0.4 on 2022-05-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diet',
            new_name='menu',
        ),
    ]
